### ISSUE TITLE
Can record and input textview or animation of imageview to video?

### ISSUE THREAD

**Issue by kazixma** [CrazyOrr/FFmpegRecorder#11]
I want to make application like SNOW app that it can write textview to video between record or input animation of imageview to video 

like this [https://www.youtube.com/watch?v=B7oIMjPd7J8](url)

Thx sir

**Comment by CrazyOrr** [comment]
To mix stuff into video, you can check out FFmpeg filters like [drawtext](https://ffmpeg.org/ffmpeg-filters.html#drawtext-1) and [overlay](https://ffmpeg.org/ffmpeg-filters.html#overlay-1).
To make those stuff stick to user's face, that requires face detection, which is out of range of this demo application.

**Comment by kazixma** [comment]
Do you have example of how to use ffmpeg overlay ? Thx

**Comment by CrazyOrr** [comment]
This application depends on [JavaCV](https://github.com/bytedeco/javacv). You can search [issues for overlay](https://github.com/bytedeco/javacv/issues?utf8=%E2%9C%93&q=overlay) there to get an idea.

**Comment by Jagdeep-Sing** [comment]
Hi @kazixma , you able to add overlay text on video? i also want same, need help
