### ISSUE TITLE
Wrong orientation in pad when portrait the pad

### ISSUE THREAD

**Issue by JoyHong** [CrazyOrr/FFmpegRecorder#12]
Dear CrazyOrr
Now, i'm adapter the pad for my app. And current we potrait the app in pad and phone.
But in pad, we preview the camera is portrait, it's ok, but when we preview the video result, it's landscape, could u please help to solve it?
Many thanks.

**Comment by CrazyOrr** [comment]
This application uses FFmpeg's [transpose filter](https://ffmpeg.org/ffmpeg-filters.html#transpose) to adjust the orientation of the video.
You should add breakpoints to watch the `info.facing` and `info.orientation` values in `VideoRecordThread` to check if the transpose applied is correct.

**Comment by JoyHong** [comment]
Yes, i complete it, thx
