### ISSUE TITLE
奇怪，项目里的ffmpeg呢？

### ISSUE THREAD

**Issue by xingwen93** [CrazyOrr/FFmpegRecorder#13]
奇怪，项目里的ffmpeg呢？

**Comment by CrazyOrr** [comment]
app/build.gradle -> dependencies -> 
`compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3'`
`compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3', classifier: 'android-arm'`
