### ISSUE TITLE
How to improve video's resolution

### ISSUE THREAD

**Issue by JoyHong** [CrazyOrr/FFmpegRecorder#14]
Dear CrazyOrr
How to improve the video's resolution ?
The demo's finnal result is not clear enough for us.

**Comment by CrazyOrr** [comment]
The video is scaled from `previewHeight` and `previewWidth` to `videoWidth` and `videoHeight`.
You can set `PREFERRED_PREVIEW_WIDTH` and `PREFERRED_PREVIEW_HEIGHT` higher to try to get a higher resolution preview.
