### ISSUE TITLE
About OOM

### ISSUE THREAD

**Issue by LoginGit** [CrazyOrr/FFmpegRecorder#18]
Thanks for your help, I encountered a new problem in your demo, I recorded the time to reach 20 seconds after the emergence of OOM,I've already seen “https://github.com/CrazyOrr/FFmpegRecorder/issues/15”, But it doesn't seem to solve my problem.

Look forward to your reply!

![image](https://cloud.githubusercontent.com/assets/24951281/22179544/f83768bc-e091-11e6-8dba-9e38d506d281.png)

**Comment by CrazyOrr** [comment]
We will discuss this issue in #15
