### ISSUE TITLE
Lib so not installed to apk

### ISSUE THREAD

**Issue by kazixma** [CrazyOrr/FFmpegRecorder#20]
The first of all , I try to install your project to my device then I can run it. When I try to install javacv by gradle dependencies , I can not use because UnsatisfiedLinkError exception. I try to monitor by Naive Lib Monitor . Lib so have inside in my apk but it didn't install to my apk. Thank

**Comment by CrazyOrr** [comment]
You can try [this](https://github.com/CrazyOrr/FFmpegRecorder/issues/8#issuecomment-261923515).

**Comment by kazixma** [comment]
@CrazyOrr  ok thank. When I use your project to record video , it's low quality of video , video is not smooth same of preview.
Ps. I choose preview 640*480 and result video 480*480. Thank

**Comment by CrazyOrr** [comment]
For video quality:
You can try to adjust this option of the `FFmpegFrameRecorder`:
`mFrameRecorder.setVideoOption("crf", "28");`
See the [doc](https://trac.ffmpeg.org/wiki/Encode/H.264#crf) for explaination.

For video size:
The size you specified is only "preferred" size, it's up to the device to match for it.
You can debug this part to figure out what happened to the size:
```java
Camera.Parameters parameters = mCamera.getParameters();
List<Camera.Size> previewSizes = parameters.getSupportedPreviewSizes();
Camera.Size previewSize = CameraHelper.getOptimalSize(previewSizes,
        PREFERRED_PREVIEW_WIDTH, PREFERRED_PREVIEW_HEIGHT);
```

**Comment by kazixma** [comment]
OK Thank and How to add autofocus to textureview preview video recorder ? Sorry for I ask too much TT

**Comment by CrazyOrr** [comment]
You can use Android Camera API's [autoFocus](https://developer.android.com/reference/android/hardware/Camera.html#autoFocus(android.hardware.Camera.AutoFocusCallback)) feature.
P.S. Usually only back-facing camera supports auto-focus feature.
