### ISSUE TITLE
App crashes after starting the recording

### ISSUE THREAD

**Issue by ajitjati** [CrazyOrr/FFmpegRecorder#26]
Hi i have used this demo project and increased but have increased PREFERRED_PREVIEW_WIDTH and PREFERRED_PREVIEW_HEIGHT but i am getting this error everytime

    com.github.crazyorr.ffmpegrecorder A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 
    0xde258000 in tid 29247 (Thread-667)

Please help

**Comment by CrazyOrr** [comment]
Try to use the latest version of JavaCV. [Similar issues](https://github.com/bytedeco/javacv/issues?utf8=%E2%9C%93&q=Fatal%20signal%2011%20(SIGSEGV)%2C%20code%201)

**Comment by ajitjati** [comment]
Yes that solved my Issue!
