### ISSUE TITLE
FC when set targetSdkVersion 23 or above

### ISSUE THREAD

**Issue by JoyHong** [CrazyOrr/FFmpegRecorder#3]
Hi
i'm using your project, but found that when i set my project targetSdkVersion is 23 or above, it's will FC.
but when i set targetSdkVersion is 22, it's ok.
Could u please help me have check?

**Comment by CrazyOrr** [comment]
It's because the permission system has changed since SDK 23. 
Beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app. So you need to requesting ("dangerous") permissions, in this case, 
android.permission.CAMERA
android.permission.RECORD_AUDIO
android.permission.WRITE_EXTERNAL_STORAGE
at run time.

**Comment by JoyHong** [comment]
Hi there
Yes, i have added this logic when start the activity, but seems still fc, and it seems occur the error in native, and i debug it, the problem seems occur in "frameRecorder = new FFmpegFrameRecorder(video, videoWidth, videoHeight, 1);"
List<String> neededPermissions = new ArrayList<String>() { {add(Manifest.permission.CAMERA); add(Manifest.permission.WRITE_EXTERNAL_STORAGE); add(Manifest.permission.RECORD_AUDIO);} };
                    List<String> deniedPermissions = new ArrayList<>();
                    for (String permission : neededPermissions) {
                        if (ActivityCompat.checkSelfPermission(JEduMomentActivity.this, permission) != PackageManager.PERMISSION_GRANTED) {
                            deniedPermissions.add(permission);
                        }
                    }
                    if (deniedPermissions.size() == 0) { // All permission are allowed
                        gotoRecordVideo();
                    } else {
                        String[] deniedArray = new String[deniedPermissions.size()];
                        deniedPermissions.toArray(deniedArray);
                        ActivityCompat.requestPermissions(JEduMomentActivity.this, deniedArray, JConstants.REQUEST_PERMISSION_VIDEO);
                    }

**Comment by CrazyOrr** [comment]
The method "initRecorder()" which contains the line "frameRecorder = new FFmpegFrameRecorder(video, videoWidth, videoHeight, 1);" gets called in a different thread than the main thread, so you may not yet get the permission when this line executed.
To try it quickly, I suggest you add another Activity as launcher, add request all the permissions in that activity, when all permissions granted, jump to the FFmpegRecordActivity.

**Comment by JoyHong** [comment]
But it seems still not work when i open all the permissions in Settings manually.

**Comment by CrazyOrr** [comment]
What is your device model? SDK version? And please paste the crash logs if you can.

**Comment by JoyHong** [comment]
Huawei honor 8
SDK version is 23, 6.0
There's no java log, but other logs

10-14 10:57:45.209 999-6265/? E/ReportTools: This is not beta user build
10-14 10:57:45.328 2421-2512/? E/PackageLogInfoManager: checkPackageLogState, cr: android.app.ContextImpl$ApplicationContentResolver@f9a37c1, packageNames: null
10-14 10:57:45.340 676-1738/? E/Camera2Client: notifyError: Error condition 0 reported by HAL, requestId -1
10-14 10:57:45.340 999-2303/? E/HsmCoreServiceImpl: onTransact in code is: 102
10-14 10:57:45.346 676-1738/? E/camera_metadata: set_camera_metadata_vendor_tag_ops: This function has been deprecated
10-14 10:57:45.356 676-1738/? E/CameraService: disconnect: Disconnect called on already disconnected client for device 0
10-14 10:57:45.356 676-1738/? E/CameraService: disconnect: Disconnect called on already disconnected client for device 0
10-14 10:57:45.356 676-1738/? E/CameraService: binderDied: Java client's binder died, removing it from the list of active clients
10-14 10:57:45.359 552-954/? E/ImagingSystem: virtual hw::TRetCode hw::CLaserManager::powerDown(hw::IImagingPipeline*, uint32_t)(125, 0x7f86a0a000): . TODO: !
10-14 10:57:45.361 2224-2639/? E/HwCustNfcServiceImpl: applyRouting -1.1
10-14 10:57:45.368 552-954/? E/ImagingSystem: virtual hw::TRetCode hw::CLaserManager::powerDownDone(hw::IImagingPipeline*, uint32_t)(134, 0x7f86a0a000): . TODO: !
10-14 10:57:45.369 552-954/? E/ImagingSystem: virtual hw::TRetCode hw::CSensorManager::powerDown(hw::IImagingPipeline*, uint32_t)(255, 0x7f872ea000): . TODO: !
10-14 10:57:45.408 552-954/? E/ImagingSystem: virtual hw::TRetCode hw::CSensorManager::powerDownDone(hw::IImagingPipeline*, uint32_t)(267, 0x7f872ea000): . TODO: !
10-14 10:57:48.638 4329-4536/? E/GmsClient: unable to connect to service: com.google.android.gms.clearcut.service.START on com.google.android.gms
10-14 10:57:48.643 4329-4536/? E/GmsClient: unable to connect to service: com.google.android.gms.phenotype.service.START on com.google.android.gms
10-14 10:57:48.647 4329-4536/? E/GmsClient: unable to connect to service: com.google.android.gms.lockbox.service.START on com.google.android.gms
10-14 10:57:48.651 4329-4536/? E/GmsClient: unable to connect to service: com.google.android.gms.usagereporting.service.START on com.google.android.gms

**Comment by CrazyOrr** [comment]
Looks like those .so libraries need to be upgraded. I'll work on that, but it'll take some time. You may have to set the targetSdkVersion 22 for now. Thanks for you reporting the issue.

**Comment by JoyHong** [comment]
Hi, many thanks.

**Comment by CrazyOrr** [comment]
You can checkout 'sdk-23-plus' branch to try it on SDK 23 or above now.
