### ISSUE TITLE
Record video with mirror effect

### ISSUE THREAD

**Issue by santoshshikare** [CrazyOrr/FFmpegRecorder#33]
I want to record video with mirror effect for front camera using this recorder, is this possible? If it is please help
thank you

**Comment by CrazyOrr** [comment]
It is possible, you can modify the logic about [transpose](http://ffmpeg.org/ffmpeg-all.html#transpose) in `VideoRecordThread`.

**Comment by santoshshikare** [comment]
Yes i have got the solution with the help of transpose.
thank you 
Your library is awesome thank you for help
