### ISSUE TITLE
Video streaming is not proper

### ISSUE THREAD

**Issue by santoshshikare** [CrazyOrr/FFmpegRecorder#34]
In some device FFmpegRecorder is not recording video properly means it stuck while recording and playing.
Device names are oneplus x , 3s prime
can you help me out for some video recorder configuration in library.

**Comment by CrazyOrr** [comment]
There are a few [configurations](https://trac.ffmpeg.org/wiki/Encode/H.264#crf) you could tune with, like:
```java
mFrameRecorder.setVideoOption("crf", "28");
mFrameRecorder.setVideoOption("preset", "superfast");
mFrameRecorder.setVideoOption("tune", "zerolatency");
```

**Comment by santoshshikare** [comment]
Ok fine
