### ISSUE TITLE
how can i set video quality

### ISSUE THREAD

**Issue by kodlayanzi** [CrazyOrr/FFmpegRecorder#38]
```
private int videoWidth = 1280;
private int videoHeight = 720;
private int frameRate = 30;
private int frameDepth = Frame.DEPTH_UBYTE;
private int frameChannels = 2;
```

i set videoHeight and videoWidth for hd quality but output video is too bad.

how can i improve the quality?

**Comment by CrazyOrr** [comment]
Refer to [this](https://github.com/CrazyOrr/FFmpegRecorder/issues/34#issuecomment-347723447).
