### ISSUE TITLE
  java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil

### ISSUE THREAD

**Issue by vanszhen** [CrazyOrr/FFmpegRecorder#39]
移植的时候报这个错，请问下 哪里配置出错了

**Comment by CrazyOrr** [comment]
[传送门](https://github.com/CrazyOrr/FFmpegRecorder/issues/8#issuecomment-261923515)

**Comment by vanszhen** [comment]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.hcf.client/app_lib/libavutil.so" is 32-bit instead of 64-bit ,  又报这个错怎么解决
