### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.hcf.client/app_lib/libavutil.so" is 32-bit instead of 64-bit 

### ISSUE THREAD

**Issue by vanszhen** [CrazyOrr/FFmpegRecorder#40]
添加 
  ReLinker.log(logger).recursively().loadLibrary(this, "avdevice");
        ReLinker.log(logger).recursively().loadLibrary(this, "avfilter");
        ReLinker.log(logger).recursively().loadLibrary(this, "avformat");
        ReLinker.log(logger).recursively().loadLibrary(this, "jniavutil");
        ReLinker.log(logger).recursively().loadLibrary(this, "avutil");
        ReLinker.log(logger).recursively().loadLibrary(this, "postproc");
        ReLinker.log(logger).recursively().loadLibrary(this, "swscale");
        ReLinker.log(logger).recursively().loadLibrary(this, "swresample");
        ReLinker.log(logger).recursively().loadLibrary(this, "jniavdevice");
        ReLinker.log(logger).recursively().loadLibrary(this, "jniavfilter");
        ReLinker.log(logger).recursively().loadLibrary(this, "jniavformat");
        ReLinker.log(logger).recursively().loadLibrary(this, "jnipostproc");
        ReLinker.log(logger).recursively().loadLibrary(this, "jniswresample");
        ReLinker.log(logger).recursively().loadLibrary(this, "jniswscale");
        ReLinker.log(logger).recursively().loadLibrary(this, "jniavcodec");
        ReLinker.log(logger).recursively().loadLibrary(this, "avcodec");

运行的时候 又报上面的错，

我用的是     minSdkVersion 15
        targetSdkVersion 26
  buildToolsVersion "26.0.2"

**Comment by CrazyOrr** [comment]
建议去[这里](https://github.com/bytedeco/javacv/issues/752)

**Comment by CrazyOrr** [comment]
JavaCV 1.4+已经支持64位
```gradle
dependencies {
    ...
    def javacvVersion = '1.4.2'
    def ffmpegVersion = '4.0.1'
    compile(group: 'org.bytedeco', name: 'javacv-platform', version: javacvVersion) {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: "${ffmpegVersion}-${javacvVersion}"
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: "${ffmpegVersion}-${javacvVersion}", classifier: 'android-arm' // for 'armeabi-v7a'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: "${ffmpegVersion}-${javacvVersion}", classifier: 'android-arm64' // for 'arm64-v8a'
}
```
