### ISSUE TITLE
App crashing on Switch and Resume recording

### ISSUE THREAD

**Issue by abhinav272** [CrazyOrr/FFmpegRecorder#43]
Firstly, Its a great sample exactly what I was looking for.

I have to integrate a similar recorder but I am facing a crash which occurs sometimes and does not provide a detail log about it.
Please see the logs below:
```com.github.crazyorr.ffmpegrecorder D/FFmpegRecordActivity: Preview frame interval: 34ms
com.github.crazyorr.ffmpegrecorder D/FFmpegRecordActivity: Preview frame interval: 46ms
com.github.crazyorr.ffmpegrecorder V/FFmpegRecordActivity: bufferReadResult: 3584
com.github.crazyorr.ffmpegrecorder A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8f07ce80 in tid 3484 (Thread-5)
                                                                        
                                                                        [ 02-12 12:47:53.949 25422:25422 W/         ]
                                                                        debuggerd: handling request: pid=3233 uid=10069 gid=10069 tid=3484
com.github.crazyorr.ffmpegrecorder D/FFmpegRecordActivity: Preview frame interval: 54ms
com.github.crazyorr.ffmpegrecorder A/libc: failed to resend signal during crash: Operation not permitted
```

This crash occurs 5 out of 8 times and usually when I pause and switch and resume again for recording or when clicking Done.

```
ext {
    versions = [
            'ffmpeg': '3.2.1-1.3'
    ]
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile(group: 'org.bytedeco', name: 'javacv-platform', version: '1.4') {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: versions.ffmpeg, classifier: 'android-arm'

    compile 'com.github.bumptech.glide:glide:3.7.0'
}
```

Thanks in advance!!

**Comment by CrazyOrr** [comment]
Glad this helps.
Try set JavaCV‘s version back to 1.3 and see if the crash occurs the same way.

**Comment by abhinav272** [comment]
Yes, I started with JavaCV 1.3 and ffmpeg version 3.2.1 same as in your sample, but since the crash occurs some where in native library I can't find a place to add try-catch so played with some combination of 1.4 & 3.4.1 but no luck.

I think the issue only occurs due to some memory being garbage collected or corrupted before accessing it.

**Comment by CrazyOrr** [comment]
If possible, retrieve the [tombstone](https://source.android.com/devices/tech/debug/native-crash#tombstones) file under `/data/tombstones/` (device may need to be rooted to see them) after the crash happens, then file a issue with this information for [JavaCV](https://github.com/bytedeco/javacv/issues?q=is%3Aissue+is%3Aopen).
