### ISSUE TITLE
is there any method to record video on removable sdcard?

### ISSUE THREAD

**Issue by anonym24** [CrazyOrr/FFmpegRecorder#44]
is there any method to record video on removable sdcard?

**Comment by CrazyOrr** [comment]
You can specify the location of recorded video by the `file` parameter when initialize `FFmpegFrameRecorder`:
```java
mFrameRecorder = new FFmpegFrameRecorder(file, videoWidth, videoHeight, 1);
```

**Comment by anonym24** [comment]
yes I know but it won't work for removable micro sd card (from Lollipop (21) there seems to be limitations) 
so I'm not talking about internal phone memory (phone sdcard), but about removable micro sdcard:

![image](https://user-images.githubusercontent.com/8851301/37297186-bfa13714-2625-11e8-93da-949f99505ee1.png)

**Comment by CrazyOrr** [comment]
Not sure about the Lollipop (21) one, you may check out the part of **Select between multiple storage locations** from the [official doc](https://developer.android.com/training/data-storage/files.html#WriteExternalStorage).

**Comment by anonym24** [comment]
the only writeable thing now seems DocumentFile, which is not File https://developer.android.com/reference/android/support/v4/provider/DocumentFile.html
to get writable DocumentFile we need to call intent
