### ISSUE TITLE
App is crashing when i open video recording page

### ISSUE THREAD

**Issue by Vibinreji** [CrazyOrr/FFmpegRecorder#48]
Hi,
    My app is crashing when i open video recording page.Demo app is working fine
![desktop screenshot](https://user-images.githubusercontent.com/13596954/42884960-54776100-8abd-11e8-97af-e267b60255d5.png)
.Here i attached the logs.

**Comment by prachi07** [comment]
Same issue i am facing.
![issue](https://user-images.githubusercontent.com/23206985/42923099-628900d0-8b41-11e8-93ef-9fe70d9a71cf.png)

**Comment by Vibinreji** [comment]
@prachi07 if u find any solution just let me know.

**Comment by prachi07** [comment]
@Vibinreji  Sure.

**Comment by CrazyOrr** [comment]
Check the 'lib' folder in your built apk, like this:
<img width="152" alt="screen shot 2018-07-19 at 3 29 08 pm" src="https://user-images.githubusercontent.com/5423309/42927959-938e31d8-8b68-11e8-8773-a014d889a095.png">
For example, if your app depends on library A and B, and library A provides native libs for both `armeabi-v7a` and `arm64-v8a`, library B provides native lib only for `armeabi-v7a`, then eventually your app would have 'lib' folder with following structure:
```
lib/
├── armeabi-v7a/                  
│   ├── liba.so // from library A
│   └── libb.so // from library B
└── arm64-v8a/
    └── liba.so // from library A
```
When the app runs on devices that only support `armeabi-v7a`, everthing is OK. But when it runs on devices support `arm64-v8a`, the system may only look into 'arm64-v8a' folder and unable to find 'libb.so' hence the `UnsatisfiedLinkError`.

This demo depends on an old version [1.3](https://search.maven.org/remotecontent?filepath=org/bytedeco/javacpp-presets/1.3/javacpp-presets-1.3.pom) of JavaCV, which only provides ffmpeg native libs for 'android-arm'(`armeabi-v7a`). If you need support for `arm64-v8a`, you should use version [1.4+](https://search.maven.org/remotecontent?filepath=org/bytedeco/javacpp-presets/1.4.2/javacpp-presets-1.4.2.pom), which provides native libs for `arm64-v8a`.
You can configure dependencies as follows:
```gradle
dependencies {
    ...
    def javacvVersion = '1.4.2'
    def ffmpegVersion = '4.0.1'
    compile(group: 'org.bytedeco', name: 'javacv-platform', version: javacvVersion) {
        exclude group: 'org.bytedeco.javacpp-presets'
    }
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: "${ffmpegVersion}-${javacvVersion}"
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: "${ffmpegVersion}-${javacvVersion}", classifier: 'android-arm' // for 'armeabi-v7a'
    compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: "${ffmpegVersion}-${javacvVersion}", classifier: 'android-arm64' // for 'arm64-v8a'
}
```

If `UnsatisfiedLinkError` still occurs after this, try [ReLinker](https://github.com/KeepSafe/ReLinker).

**Comment by Vibinreji** [comment]
Thankyou @CrazyOrr

**Comment by prachi07** [comment]
Thanks @CrazyOrr.
