### ISSUE TITLE
After Video recording preview video quality is lagging .

### ISSUE THREAD

**Issue by harshbhavsar011** [CrazyOrr/FFmpegRecorder#49]
private int sampleAudioRateInHz = 44100;    
     private int frameRate = 30;

       mFrameRecorder.setFormat("mp4");
        mFrameRecorder.setSampleRate(sampleAudioRateInHz);
        mFrameRecorder.setFrameRate(frameRate);

        // Use H264
        mFrameRecorder.setVideoCodec(avcodec.AV_CODEC_ID_H264);
        mFrameRecorder.setVideoOption("crf", "14");
        mFrameRecorder.setVideoOption("preset", "ultrafast");
        mFrameRecorder.setVideoOption("tune", "film");

**Comment by CrazyOrr** [comment]
As suggested in [this issue](https://github.com/CrazyOrr/FFmpegRecorder/issues/47#issuecomment-406317016), we need hardware acceleration support to encode video.
