### ISSUE TITLE
How can i export this application to aar library

### ISSUE THREAD

**Issue by matart15** [CrazyOrr/FFmpegRecorder#5]
I want to use `FFmpegRecordActivity` from Nativescript. 
For that I have to export application to aar library and call `FFmpegRecordActivity` class from javascript via Intent. 

I did that part It worked.

But after `FFmpegRecordActivity` is displayed it breaks with this error.

    java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
    at java.lang.Class.classForName(Native Method)
    at java.lang.Class.forName(Class.java:309)
    at org.bytedeco.javacpp.Loader.load(Loader.java:413)
    at org.bytedeco.javacpp.Loader.load(Loader.java:381)
    at org.bytedeco.javacpp.avcodec$AVPacket.<clinit>(avcodec.java:1650)

It seems not nativescript problem. Because same thing happened when i import aar from another android studio application.

camera, external storage permissions are given and on for application

----------
 I did the trick from https://github.com/bytedeco/javacv/issues/133 : moved *.so files to "app/src/main/jniLibs/armeabi-v7a" and "app/src/main/jniLibs/armeabi" folders and it seems not working

**Comment by CrazyOrr** [comment]
Can you run this application directly (not exporting as aar library) on your testing device successfully without the "UnsatisfiedLinkError" you mention?

**Comment by matart15** [comment]
Application run directly in my phone without problem.

I asked same question on JavaCpp repo.
https://github.com/bytedeco/javacpp-presets/issues/303

It seems *.so file related. But i have no idea how to import them correctly.

**Comment by matart15** [comment]
I am not very famillar with android and java development.

project I trying to create aar is this. (https://github.com/matart15/FFmpegRecorder)
project I trying to use that aar is this (https://github.com/matart15/FFmpegRecorder_loader)

If you have time can you look into it. Please. 

I am pulling all my hairs here

**Comment by matart15** [comment]
I used this app to see copied libs.
https://play.google.com/store/apps/details?id=com.xh.nativelibsmonitor.app&hl=en
![screenshot_20161017-121132](https://cloud.githubusercontent.com/assets/17027219/19424334/38d59856-9463-11e6-8f50-2491416d2ea5.png)

if this app working right then *.so files seems copied.

Is it possible that *.so files are copied and not being referenced?

**Comment by CrazyOrr** [comment]
The problem is this application currently not working on sdk version 23 or above. (See #3 )
When you import this application as aar library, the targetSdkVersion of the library, which is 22 (https://github.com/CrazyOrr/FFmpegRecorder/blob/master/app/build.gradle), gets overrided by your application's targetSdkVersion, which is 24 (https://github.com/matart15/FFmpegRecorder_loader/blob/master/app/build.gradle), hence the "UnsatisfiedLinkError" occurs. But when you run this application directly, the targetSdkVersion 22 is honored, so no error.

**Comment by matart15** [comment]
Thank you It was sqk version. My app worked.

**Comment by CrazyOrr** [comment]
You can checkout 'sdk-23-plus' branch to try it on SDK 23 or above now.

**Comment by matart15** [comment]
Thank you I will do that.
