### ISSUE TITLE
LandScape Full Screen Video

### ISSUE THREAD

**Issue by ArindamAndroid** [CrazyOrr/FFmpegRecorder#56]
When i rotate the device in landscape mode then video preview is not full screen.. how i preview the video full screen in landscape mode.?

**Comment by CrazyOrr** [comment]
Just make the `TextureView` fullscreen and set `PREFERRED_PREVIEW_WIDTH`/`PREFERRED_PREVIEW_HEIGHT` and `videoWidth`/`videoHeight` in accordance with the screen size.
