### ISSUE TITLE
long recording and encoding delay

### ISSUE THREAD

**Issue by tingfengainiaini** [CrazyOrr/FFmpegRecorder#6]
I found that the recording is so long delayed by encoding into video. 
The mRecordedFrameQueue is behind the preview so much. So, I should wait a long time after I press the stop button which invoke the stopRecording().
Is there any solution to solve this ?

**Comment by tingfengainiaini** [comment]
Solved!
```
mFrameRecorder.setVideoOption("tune", "zerolatency");
mFrameRecorder.setVideoOption("preset", "superfast");
mFrameRecorder.setVideoOption("crf", Integer.toString(param.getVideoFrameRate()));
```

**Comment by CrazyOrr** [comment]
Well, it's a tradeoff between video quality and speed. 
I have implemented a simple "drop-frame-if-could-not-keep-up" strategy in this, but it is far from good. Ideally, we need an algorithm to adjust dynamically towards the balance point.
