### ISSUE TITLE
Muxing of Audio with recorded video

### ISSUE THREAD

**Issue by SuryaChundawat** [CrazyOrr/FFmpegRecorder#60]
Can you please help me out how to mux audio with recoded video.

**Comment by CrazyOrr** [comment]
I think the demo has [this](https://github.com/CrazyOrr/FFmpegRecorder/blob/master/app/src/main/java/com/github/crazyorr/ffmpegrecorder/FFmpegRecordActivity.java#L604) to do muxing.

**Comment by SuryaChundawat** [comment]
Thanks
