### ISSUE TITLE
conflict in FFmpeg repository

### ISSUE THREAD

**Issue by SuryaChundawat** [CrazyOrr/FFmpegRecorder#61]
if I am using this library along with writingminds library 'com.writingminds:FFmpegAndroid:0.3.2' . Wirtingminds library doesn't work properly.

**Comment by CrazyOrr** [comment]
I don't know about that library but I don't think you should use multiple libraries encapsulating FFmpeg.

**Comment by SuryaChundawat** [comment]
> I don't know about that library but I don't think you should use multiple libraries encapsulating FFmpeg.

I got the solution. Thanks for your time. I am facing one new isuue how to add filters while recording a video.

**Comment by SuryaChundawat** [comment]
Its support both.
