### ISSUE TITLE
APK is too large

### ISSUE THREAD

**Issue by airtayork** [CrazyOrr/FFmpegRecorder#9]
The single record demo APK is about 12.7M,too large to integrate into a project.Any way to shrink the size?

**Comment by CrazyOrr** [comment]
The entire FFmpeg libraries takes about 10.4M, but not all of the functions are used to record video, so it should be possible to rebuild a more "concise" one yourself. 
Build reference: [https://github.com/bytedeco/javacpp-presets/wiki/Build-Environments](url)

**Comment by airtayork** [comment]
Thank you,I'll try...

**Comment by levon93** [comment]
@airtayork did you manage to do that?
